import type { Metadata } from "next";
import localFont from "next/font/local";
import { Didact_Gothic, Exo_2, Montserrat_Alternates } from "next/font/google";
import { Toaster } from "@/components/Shared/Sonner";
import "./globals.css";

const didact_gothic = Didact_Gothic({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-one",
});

const exo_2 = Exo_2({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-two",
});

const montserrat_alternates = Montserrat_Alternates({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-three",
});

const walkway = localFont({
  src: [
    {
      path: "./../public/fonts/Walkway_Bold.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../public/fonts/Walkway_Black.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-cuatro", // optionnel : te permet d’utiliser la font comme variable CSS
  display: "swap", // bon pour les performances
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${didact_gothic.variable} ${exo_2.variable} ${montserrat_alternates.variable} ${walkway.variable} antialiased relative`}
      >
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}
